# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:lts

    steps:
      - checkout
      - run: node --version
      - run: yarn install --immutable
      - run: yarn ci
